digraph makefile
{
    foobar_ex [label="foobar executable"]
    foo_c [label="foo.c"]
    bar_c [label="bar.c"]
    foo_o [label="foo.o"]
    bar_o [label="bar.o"]
    foo_c -> foo_o
    bar_c -> bar_o
    foo_o -> foobar_ex
    bar_o -> foobar_ex
}